/*
 * This source file was generated by the Gradle 'init' task
 */
package dice;
import dice.model.*;
import dice.controller.*;

public class App {
    public static void main(String[] args) {
        Dice dice = new Dice(3);
        AnimatedDiceController controller = new AnimatedDiceController(dice);
    }
}
